import './globals.css'
import Header from './layouts/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body className='bg-neutral-bg dark:bg-neutral-dark-bg'>
        <Header />
        {children}
      </body>
    </html>
  )
}
